
define bare? bare
namespace bare


OSSize              := $020104
BootOS              := $020108
interruptHandler    := $02010C
rst10Handler        := $020110
rst18Handler        := $020114
rst20Handler        := $020118
rst28Handler        := $02011C
rst30Handler        := $020120
fs_find_sym         := $020124
fs_execute_file     := $020128
fs_create_file      := $02012C
fs_delete_file      := $020130



end namespace
